#!/bin/bash

echo "═══════════════════════════════════════════════════"
echo "🔍 VERIFICAÇÃO DO TOKEN NO RENDER"
echo "═══════════════════════════════════════════════════"
echo ""
echo "Execute este comando no Shell do Render:"
echo ""
echo "  echo \"WHATSAPP_VERIFY_TOKEN=\$WHATSAPP_VERIFY_TOKEN\""
echo ""
echo "Ou verifique o comprimento:"
echo ""
echo "  echo \${#WHATSAPP_VERIFY_TOKEN}"
echo ""
echo "Compare com o esperado:"
echo "  Token: fono-inova-verify-2025"
echo "  Comprimento: 22"
echo ""
echo "═══════════════════════════════════════════════════"
